"""Initial schema with auth

Revision ID: 13cb694df246
Revises: 
Create Date: 2025-12-23 09:48:25.784791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '13cb694df246'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('original_instruction', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_conditions', sa.JSON(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_one_time', sa.Boolean(), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('last_execution_result', sa.JSON(), nullable=True),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('next_scheduled_run', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_automation_status', 'automation_rules', ['status'], unique=False)
    op.create_index('idx_automation_team', 'automation_rules', ['team_id'], unique=False)
    op.create_index('idx_automation_trigger', 'automation_rules', ['trigger_type'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('team_id', sa.String(length=100), nullable=False),
    sa.Column('channel_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('conversation_type', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('extracted_actions', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index('idx_conversation_team', 'conversations', ['team_id'], unique=False)
    op.create_index('idx_conversation_thread', 'conversations', ['thread_id'], unique=False)
    op.create_index('idx_conversation_type', 'conversations', ['conversation_type'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('alternatives_considered', sa.JSON(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('decided_by', sa.String(length=100), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('affected_files', sa.JSON(), nullable=True),
    sa.Column('affected_components', sa.JSON(), nullable=True),
    sa.Column('affected_users', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('importance', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('superseded_by', sa.String(length=36), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_decision_created', 'decisions', ['created_at'], unique=False)
    op.create_index('idx_decision_source', 'decisions', ['source_type', 'source_id'], unique=False)
    op.create_index('idx_decision_status', 'decisions', ['status'], unique=False)
    op.create_index('idx_decision_team', 'decisions', ['team_id'], unique=False)
    op.create_table('file_ownership',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('team_id', sa.String(length=100), nullable=False),
    sa.Column('user_identifier', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('ownership_score', sa.Float(), nullable=True),
    sa.Column('total_commits', sa.Integer(), nullable=True),
    sa.Column('total_lines_added', sa.Integer(), nullable=True),
    sa.Column('total_lines_removed', sa.Integer(), nullable=True),
    sa.Column('first_commit_at', sa.DateTime(), nullable=True),
    sa.Column('last_commit_at', sa.DateTime(), nullable=True),
    sa.Column('recent_activity_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ownership_file', 'file_ownership', ['file_path', 'repo'], unique=False)
    op.create_index('idx_ownership_score', 'file_ownership', ['ownership_score'], unique=False)
    op.create_index('idx_ownership_team', 'file_ownership', ['team_id'], unique=False)
    op.create_index('idx_ownership_user', 'file_ownership', ['user_identifier'], unique=False)
    op.create_table('github_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('repository', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=True),
    sa.Column('sender_id', sa.String(length=100), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processing_result', sa.JSON(), nullable=True),
    sa.Column('impact_analyzed', sa.Boolean(), nullable=True),
    sa.Column('affected_users', sa.JSON(), nullable=True),
    sa.Column('affected_files', sa.JSON(), nullable=True),
    sa.Column('notifications_sent', sa.JSON(), nullable=True),
    sa.Column('is_breaking_change', sa.Boolean(), nullable=True),
    sa.Column('change_category', sa.String(length=50), nullable=True),
    sa.Column('team_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_github_event_type', 'github_events', ['event_type'], unique=False)
    op.create_index('idx_github_pr', 'github_events', ['pr_number'], unique=False)
    op.create_index('idx_github_processed', 'github_events', ['processed'], unique=False)
    op.create_index('idx_github_repository', 'github_events', ['repository'], unique=False)
    op.create_index('idx_github_sender', 'github_events', ['sender'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_teams', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('allowed_domains', sa.JSON(), nullable=True),
    sa.Column('github_org', sa.String(length=100), nullable=True),
    sa.Column('slack_workspace_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_org_slug', 'organizations', ['slug'], unique=False)
    op.create_table('productivity_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_identifier', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.String(length=100), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('commits_count', sa.Integer(), nullable=True),
    sa.Column('prs_opened', sa.Integer(), nullable=True),
    sa.Column('prs_merged', sa.Integer(), nullable=True),
    sa.Column('prs_reviewed', sa.Integer(), nullable=True),
    sa.Column('issues_closed', sa.Integer(), nullable=True),
    sa.Column('comments_made', sa.Integer(), nullable=True),
    sa.Column('tasks_created', sa.Integer(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('tasks_in_progress', sa.Integer(), nullable=True),
    sa.Column('lines_added', sa.Integer(), nullable=True),
    sa.Column('lines_removed', sa.Integer(), nullable=True),
    sa.Column('files_changed', sa.Integer(), nullable=True),
    sa.Column('knowledge_entries_created', sa.Integer(), nullable=True),
    sa.Column('decisions_made', sa.Integer(), nullable=True),
    sa.Column('productivity_score', sa.Float(), nullable=True),
    sa.Column('metrics_detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_date', 'productivity_snapshots', ['snapshot_date'], unique=False)
    op.create_index('idx_snapshot_team', 'productivity_snapshots', ['team_id'], unique=False)
    op.create_index('idx_snapshot_user', 'productivity_snapshots', ['user_identifier'], unique=False)
    op.create_index('idx_snapshot_user_date', 'productivity_snapshots', ['user_identifier', 'snapshot_date'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('team_id', sa.String(length=100), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('assigned_to_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=True),
    sa.Column('blocks', sa.JSON(), nullable=True),
    sa.Column('related_files', sa.JSON(), nullable=True),
    sa.Column('related_prs', sa.JSON(), nullable=True),
    sa.Column('related_decision_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by_automation', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_assigned', 'tasks', ['assigned_to'], unique=False)
    op.create_index('idx_task_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('idx_task_priority', 'tasks', ['priority'], unique=False)
    op.create_index('idx_task_status', 'tasks', ['status'], unique=False)
    op.create_index('idx_task_team', 'tasks', ['team_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verification_token', sa.String(length=100), nullable=True),
    sa.Column('password_reset_token', sa.String(length=100), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('github_id', sa.String(length=100), nullable=True),
    sa.Column('github_username', sa.String(length=100), nullable=True),
    sa.Column('slack_id', sa.String(length=100), nullable=True),
    sa.Column('slack_username', sa.String(length=100), nullable=True),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.Column('current_org_id', sa.String(length=36), nullable=True),
    sa.Column('current_team_id', sa.String(length=36), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('dashboard_layout', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('slack_id')
    )
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_github', 'users', ['github_id'], unique=False)
    op.create_index('idx_user_slack', 'users', ['slack_id'], unique=False)
    op.create_table('automation_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('triggered_by_event', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('actions_performed', sa.JSON(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_execution_rule', 'automation_executions', ['rule_id'], unique=False)
    op.create_index('idx_execution_status', 'automation_executions', ['status'], unique=False)
    op.create_index('idx_execution_time', 'automation_executions', ['executed_at'], unique=False)
    op.create_table('decision_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('challenger_id', sa.String(length=100), nullable=False),
    sa.Column('challenge_reason', sa.Text(), nullable=False),
    sa.Column('proposed_alternative', sa.Text(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('retrieved_context', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_challenge_decision', 'decision_challenges', ['decision_id'], unique=False)
    op.create_index('idx_challenge_status', 'decision_challenges', ['status'], unique=False)
    op.create_table('knowledge_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('team_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('is_actionable', sa.Boolean(), nullable=True),
    sa.Column('extracted_entities', sa.JSON(), nullable=True),
    sa.Column('extracted_action_items', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('related_decision_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['related_decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_actionable', 'knowledge_entries', ['is_actionable'], unique=False)
    op.create_index('idx_knowledge_category', 'knowledge_entries', ['category'], unique=False)
    op.create_index('idx_knowledge_created_at', 'knowledge_entries', ['created_at'], unique=False)
    op.create_index('idx_knowledge_source', 'knowledge_entries', ['source'], unique=False)
    op.create_index('idx_knowledge_team_id', 'knowledge_entries', ['team_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('context_used', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_message_created_at', 'messages', ['created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_identifier', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.String(length=100), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('related_change', sa.JSON(), nullable=True),
    sa.Column('affected_files', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('is_actioned', sa.Boolean(), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('delivery_channels', sa.JSON(), nullable=True),
    sa.Column('delivered_via_slack', sa.Boolean(), nullable=True),
    sa.Column('delivered_via_email', sa.Boolean(), nullable=True),
    sa.Column('slack_message_ts', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_created', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notification_read', 'notifications', ['is_read'], unique=False)
    op.create_index('idx_notification_team', 'notifications', ['team_id'], unique=False)
    op.create_index('idx_notification_type', 'notifications', ['notification_type'], unique=False)
    op.create_index('idx_notification_user', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notification_user_identifier', 'notifications', ['user_identifier'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('custom_permissions', sa.JSON(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_org_member_org', 'organization_members', ['organization_id'], unique=False)
    op.create_index('idx_org_member_user', 'organization_members', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('github_repos', sa.JSON(), nullable=True),
    sa.Column('slack_channels', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_org', 'teams', ['organization_id'], unique=False)
    op.create_index('idx_team_slug', 'teams', ['slug'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_identifier', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.String(length=100), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('related_files', sa.JSON(), nullable=True),
    sa.Column('related_task_id', sa.String(length=36), nullable=True),
    sa.Column('related_pr_number', sa.Integer(), nullable=True),
    sa.Column('related_repo', sa.String(length=255), nullable=True),
    sa.Column('lines_added', sa.Integer(), nullable=True),
    sa.Column('lines_removed', sa.Integer(), nullable=True),
    sa.Column('files_changed', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_source', 'user_activities', ['source', 'source_id'], unique=False)
    op.create_index('idx_activity_team', 'user_activities', ['team_id'], unique=False)
    op.create_index('idx_activity_timestamp', 'user_activities', ['timestamp'], unique=False)
    op.create_index('idx_activity_type', 'user_activities', ['activity_type'], unique=False)
    op.create_index('idx_activity_user', 'user_activities', ['user_id'], unique=False)
    op.create_index('idx_activity_user_identifier', 'user_activities', ['user_identifier'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_invite_email', 'invites', ['email'], unique=False)
    op.create_index('idx_invite_org', 'invites', ['organization_id'], unique=False)
    op.create_index('idx_invite_token', 'invites', ['token'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_team_member_team', 'team_members', ['team_id'], unique=False)
    op.create_index('idx_team_member_user', 'team_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_team_member_user', table_name='team_members')
    op.drop_index('idx_team_member_team', table_name='team_members')
    op.drop_table('team_members')
    op.drop_index('idx_invite_token', table_name='invites')
    op.drop_index('idx_invite_org', table_name='invites')
    op.drop_index('idx_invite_email', table_name='invites')
    op.drop_table('invites')
    op.drop_index('idx_activity_user_identifier', table_name='user_activities')
    op.drop_index('idx_activity_user', table_name='user_activities')
    op.drop_index('idx_activity_type', table_name='user_activities')
    op.drop_index('idx_activity_timestamp', table_name='user_activities')
    op.drop_index('idx_activity_team', table_name='user_activities')
    op.drop_index('idx_activity_source', table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index('idx_team_slug', table_name='teams')
    op.drop_index('idx_team_org', table_name='teams')
    op.drop_table('teams')
    op.drop_index('idx_org_member_user', table_name='organization_members')
    op.drop_index('idx_org_member_org', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index('idx_notification_user_identifier', table_name='notifications')
    op.drop_index('idx_notification_user', table_name='notifications')
    op.drop_index('idx_notification_type', table_name='notifications')
    op.drop_index('idx_notification_team', table_name='notifications')
    op.drop_index('idx_notification_read', table_name='notifications')
    op.drop_index('idx_notification_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_message_created_at', table_name='messages')
    op.drop_index('idx_message_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_knowledge_team_id', table_name='knowledge_entries')
    op.drop_index('idx_knowledge_source', table_name='knowledge_entries')
    op.drop_index('idx_knowledge_created_at', table_name='knowledge_entries')
    op.drop_index('idx_knowledge_category', table_name='knowledge_entries')
    op.drop_index('idx_knowledge_actionable', table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_index('idx_challenge_status', table_name='decision_challenges')
    op.drop_index('idx_challenge_decision', table_name='decision_challenges')
    op.drop_table('decision_challenges')
    op.drop_index('idx_execution_time', table_name='automation_executions')
    op.drop_index('idx_execution_status', table_name='automation_executions')
    op.drop_index('idx_execution_rule', table_name='automation_executions')
    op.drop_table('automation_executions')
    op.drop_index('idx_user_slack', table_name='users')
    op.drop_index('idx_user_github', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_task_team', table_name='tasks')
    op.drop_index('idx_task_status', table_name='tasks')
    op.drop_index('idx_task_priority', table_name='tasks')
    op.drop_index('idx_task_due_date', table_name='tasks')
    op.drop_index('idx_task_assigned', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_snapshot_user_date', table_name='productivity_snapshots')
    op.drop_index('idx_snapshot_user', table_name='productivity_snapshots')
    op.drop_index('idx_snapshot_team', table_name='productivity_snapshots')
    op.drop_index('idx_snapshot_date', table_name='productivity_snapshots')
    op.drop_table('productivity_snapshots')
    op.drop_index('idx_org_slug', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('idx_github_sender', table_name='github_events')
    op.drop_index('idx_github_repository', table_name='github_events')
    op.drop_index('idx_github_processed', table_name='github_events')
    op.drop_index('idx_github_pr', table_name='github_events')
    op.drop_index('idx_github_event_type', table_name='github_events')
    op.drop_table('github_events')
    op.drop_index('idx_ownership_user', table_name='file_ownership')
    op.drop_index('idx_ownership_team', table_name='file_ownership')
    op.drop_index('idx_ownership_score', table_name='file_ownership')
    op.drop_index('idx_ownership_file', table_name='file_ownership')
    op.drop_table('file_ownership')
    op.drop_index('idx_decision_team', table_name='decisions')
    op.drop_index('idx_decision_status', table_name='decisions')
    op.drop_index('idx_decision_source', table_name='decisions')
    op.drop_index('idx_decision_created', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('idx_conversation_type', table_name='conversations')
    op.drop_index('idx_conversation_thread', table_name='conversations')
    op.drop_index('idx_conversation_team', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_automation_trigger', table_name='automation_rules')
    op.drop_index('idx_automation_team', table_name='automation_rules')
    op.drop_index('idx_automation_status', table_name='automation_rules')
    op.drop_table('automation_rules')
    # ### end Alembic commands ###
